[package]
name = "cocoa"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
dirs = "5.0.1"
hostname = "0.4.0"
rustyline = "14.0.0"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
